// <auto-generated>
// The convention checks, generated from the plugin's rule list. Do not edit: a new plugin release replaces this
// file. Switch a check off in conventions-check.json beside this project.
// </auto-generated>
using System.Collections.Generic;

namespace ConventionsCheck;

public static class ConventionChecks
{
    public static IReadOnlyList<ConventionCheck> All { get; } =
    [
        new()
        {
            Id = @"no-configureawait",
            Scope = @"fragment",
            Lang = @"cs",
            Kind = @"line",
            Message = @"no .ConfigureAwait(false) in service, module or library code",
            Patterns =
            [
                new()
                {
                    Pattern = @"\.ConfigureAwait\(\s*false\s*\)",
                },
            ],
        },
        new()
        {
            Id = @"json-name-repeats-default",
            Scope = @"fragment",
            Lang = @"cs",
            Kind = @"text",
            Message = @"a JsonPropertyName that only repeats the default camelCase name",
            Pattern = @"\[(?:property:\s*)?JsonPropertyName\(""(?<json>[^""]*)""\)\]\s*(?:(?:public|private|protected|internal|required|virtual|override|static|readonly)\s+)*[\w.<>?,\[\] ]+?\s+(?<name>[\p{L}_]\w*)\s*(?:[{;=,)]|$)",
            Compare = @"camelEqual",
            LiteralGroup = @"json",
        },
        new()
        {
            Id = @"endpoint-file-layout",
            Scope = @"file",
            Lang = @"cs",
            Kind = @"types",
            Message = @"an {Op}Endpoint.cs holds one type; an {Op}Command.cs or {Op}Query.cs holds the request and its {Request}Validator",
            Rule = @"endpoint-layout",
        },
        new()
        {
            Id = @"one-type-per-file",
            Scope = @"file",
            Lang = @"cs",
            Kind = @"types",
            Message = @"one type per file (a command or query file, a Models.cs, delegates beside their interface and an I{Name}.cs holding its interface with the records and enums its members name excepted)",
            Rule = @"one-per-file",
        },
        new()
        {
            Id = @"not-found-by-hand",
            Scope = @"fragment",
            Lang = @"cs",
            Kind = @"line",
            Message = @"not-found goes through the guard helpers and the central error mapper, never a hand-built reply",
            LibraryHalf = true,
            Patterns =
            [
                new()
                {
                    Pattern = @"\bSend\.NotFoundAsync\(|\bSendNotFoundAsync\(|\b(?:Typed)?Results\.NotFound\(|\bStatusCode\(\s*(?:StatusCodes\.)?(?:Status404NotFound|404)\b",
                },
            ],
        },
        new()
        {
            Id = @"auth-in-handler",
            Scope = @"fragment",
            Lang = @"cs",
            Kind = @"line",
            Message = @"access is declared on the endpoint or held by an authorization handler, never a hand-written 403",
            Patterns =
            [
                new()
                {
                    Pattern = @"\bSend\.ForbiddenAsync\(|\bSendForbiddenAsync\(|\b(?:Typed)?Results\.Forbid\(|\bStatusCode\(\s*(?:StatusCodes\.)?(?:Status403Forbidden|403)\b",
                },
            ],
        },
        new()
        {
            Id = @"settings-by-hand",
            Scope = @"fragment",
            Lang = @"cs",
            Kind = @"line",
            Message = @"settings are bound by the bind-and-validate helper and injected, never read by key or bound by hand",
            LibraryHalf = true,
            UnlessText = @"\bIServiceCollection\b|\bWebApplication\.CreateBuilder\b|\bIHostApplicationBuilder\b",
            Patterns =
            [
                new()
                {
                    Pattern = @"\b[Cc]onfig(?:uration)?\s*\[\s*""|\.GetSection\(",
                },
            ],
        },
        new()
        {
            Id = @"central-versions",
            Scope = @"fragment",
            Lang = @"project",
            Kind = @"text",
            Message = @"package versions live in the central package file, never on a PackageReference",
            Pattern = @"<PackageReference\b[^>]*?\bVersion\s*=",
        },
        new()
        {
            Id = @"project-file-basics",
            Scope = @"fragment",
            Lang = @"project",
            Kind = @"line",
            Message = @"a project file sets the basics only: no documentation file, no warning suppression, no comment — a pinned package excepted",
            Patterns =
            [
                new()
                {
                    Pattern = @"<GenerateDocumentationFile>",
                },
                new()
                {
                    Pattern = @"<NoWarn>",
                    Unless = @"<NoWarn>\s*(?:\$\(NoWarn\)\s*[;,]?\s*)?(?:NU\d{4}\s*[;,]?\s*)+</NoWarn>",
                },
                new()
                {
                    Pattern = @"<!--",
                    UnlessNext = @"^\s*<Package(?:Version|Reference)\b",
                },
            ],
        },
        new()
        {
            Id = @"shared-namespace",
            Scope = @"fragment",
            Lang = @"cs",
            Kind = @"line",
            Message = @"a _Shared folder's namespace is .Shared, without the underscore",
            Patterns =
            [
                new()
                {
                    Pattern = @"\b(?:namespace|using)\s+[\w.]*\._Shared\b",
                },
            ],
        },
        new()
        {
            Id = @"no-doc-comments",
            Scope = @"fragment",
            Lang = @"cs",
            Kind = @"line",
            Message = @"no documentation comments: the name says what a thing does",
            LibraryHalf = true,
            Comments = true,
            Patterns =
            [
                new()
                {
                    Pattern = @"^\s*///",
                },
            ],
        },
        new()
        {
            Id = @"no-dividers",
            Scope = @"fragment",
            Lang = @"cs",
            Kind = @"line",
            Message = @"no divider comments; a file that needs sections is too long",
            Comments = true,
            Patterns =
            [
                new()
                {
                    Pattern = @"^\s*(?://+|/\*+)\s*([-=*#~_])\1{2,}",
                },
            ],
        },
        new()
        {
            Id = @"no-markers-todo",
            Scope = @"fragment",
            Lang = @"cs",
            Kind = @"line",
            Message = @"no to-do comments and no //insight or //talk markers in committed code",
            Comments = true,
            Patterns =
            [
                new()
                {
                    Pattern = @"(?://|/\*)\s*(?:TODO|FIXME|HACK)\b",
                    Flags = @"i",
                },
                new()
                {
                    Pattern = @"//\s*(?:insight|talk)\s*[-:]",
                    Flags = @"i",
                },
            ],
        },
        new()
        {
            Id = @"no-argument-preamble",
            Scope = @"fragment",
            Lang = @"cs",
            Kind = @"line",
            Message = @"no argument-checking preamble in service code: inputs are validated at the edge",
            LibraryHalf = true,
            Patterns =
            [
                new()
                {
                    Pattern = @"\bArgument(?:Null|OutOfRange)?Exception\.Throw\w*\(|\bthrow\s+new\s+Argument(?:Null|OutOfRange)?Exception\(",
                },
            ],
        },
        new()
        {
            Id = @"token-name",
            Scope = @"fragment",
            Lang = @"cs",
            Kind = @"line",
            Message = @"a cancellation token parameter is named ct",
            Patterns =
            [
                new()
                {
                    Pattern = @"(?:[(,]|^)\s*(?:\[[^\]]*\]\s*)?CancellationToken\s+(?<name>[\p{L}_]\w*)\s*(?:[,)]|=\s*default\b|$)",
                    Unless = @"\boverride\b|\b(?:StartAsync|StopAsync)\s*\(",
                    NameMust = @"^ct$",
                },
            ],
        },
        new()
        {
            Id = @"async-suffix",
            Scope = @"fragment",
            Lang = @"cs",
            Kind = @"line",
            Message = @"an asynchronous method ends in Async (names a framework fixes apart)",
            Patterns =
            [
                new()
                {
                    Pattern = @"^\s*(?:(?:public|private|protected|internal|static|virtual|override|abstract|sealed|new|async|extern|unsafe|partial)\s+)*(?:Task|ValueTask)(?:<.*>)?\s+(?<name>[\p{L}_]\w*)\s*(?:<[^>()]*>)?\s*\(",
                    Unless = @"\boverride\b",
                    NameMust = @"(?:Async|^(?:Handle|Consume|Invoke|Execute|Main))$",
                },
            ],
        },
        new()
        {
            Id = @"no-sealed",
            Scope = @"fragment",
            Lang = @"cs",
            Kind = @"line",
            Message = @"classes are not sealed by default; only a framework-facing leaf type may be",
            Patterns =
            [
                new()
                {
                    Pattern = @"\bsealed\s+(?:partial\s+)?(?:class|record)\s+(?:class\s+|struct\s+)?(?<name>[\p{L}_]\w*)",
                    NameMust = @"(?:Middleware|Filter|Consumer|Publisher|Scope|DesignTimeDbContextFactory|DesignTimeFactory)$",
                },
            ],
        },
        new()
        {
            Id = @"is-null",
            Scope = @"fragment",
            Lang = @"cs",
            Kind = @"line",
            Message = @"is null / is not null in statements; == null only inside a query",
            Patterns =
            [
                new()
                {
                    Pattern = @"[!=]=\s*null\b|\bnull\s*[!=]=",
                    Unless = @"=>|^\s*(?:&&|\|\||where\b|from\b|let\b|join\b|select\b|orderby\b|on\b|\?|:)",
                },
            ],
        },
        new()
        {
            Id = @"constant-names",
            Scope = @"fragment",
            Lang = @"cs",
            Kind = @"line",
            Message = @"a constant is PascalCase, in a class and inside a method alike",
            Patterns =
            [
                new()
                {
                    Pattern = @"\bconst\s+[\w.?]+(?:<[^>]*>)?(?:\[\])?\s+(?<name>[\p{L}_]\w*)\s*=",
                    NameMust = @"^\p{Lu}[\p{L}\p{Nd}]*$",
                },
            ],
        },
        new()
        {
            Id = @"attribute-order",
            Scope = @"fragment",
            Lang = @"cs",
            Kind = @"order",
            Message = @"a FastEndpoints endpoint's attributes come in the order authorization, route, tags",
            Groups = [@"^\s*\[(?:Authorize|AllowAnonymous)\b", @"^\s*\[(?:Http(?:Get|Post|Put|Patch|Delete|Head|Options)|Route)\b", @"^\s*\[Tags\b"],
        },
        new()
        {
            Id = @"record-members-pascal",
            Scope = @"fragment",
            Lang = @"cs",
            Kind = @"text",
            Message = @"a record's positional members are PascalCase",
            Pattern = @"\brecord\s+(?:class\s+|struct\s+)?[\p{L}_]\w*(?:<[^<>()]*>)?\s*\((?<params>[^()]*)\)",
            ParamsMust = @"^\p{Lu}",
        },
        new()
        {
            Id = @"logging-allow-list",
            Scope = @"file",
            Lang = @"cs",
            Kind = @"types",
            Message = @"a class logs only when it is on the lists file's logging list or is a hosted service, job, worker, middleware, pipeline behaviour or the central error handler",
            Rule = @"logging",
            AllowName = @"(?:HostedService|BackgroundService|Job|Worker|Middleware|Behavior|Behaviour|ExceptionHandler|ErrorHandler)$",
            AllowBase = @"\b(?:BackgroundService|IHostedService|IMiddleware|IPipelineBehavior<|IExceptionHandler|IJob)\b",
        },
        new()
        {
            Id = @"no-mapping-library",
            Scope = @"fragment",
            Lang = @"cs",
            Kind = @"line",
            Message = @"mapping between shapes is written by hand, never through a mapping library",
            Patterns =
            [
                new()
                {
                    Pattern = @"\.Adapt<|\.Adapt\(|\bTypeAdapterConfig\b|\.ProjectToType<|\bAddMapster\(|\bAddAutoMapper\(|^\s*using\s+(?:Mapster|AutoMapper)\b",
                },
            ],
        },
        new()
        {
            Id = @"injected-clock",
            Scope = @"fragment",
            Lang = @"cs",
            Kind = @"line",
            Message = @"the time comes from the injected clock (TimeProvider), never the system clock",
            LibraryHalf = true,
            Patterns =
            [
                new()
                {
                    Pattern = @"\bDateTime(?:Offset)?\.(?:UtcNow|Now)\b",
                },
            ],
        },
        new()
        {
            Id = @"no-null-default-dependency",
            Scope = @"fragment",
            Lang = @"cs",
            Kind = @"line",
            Message = @"every dependency is required: no interface-typed parameter defaults to null",
            Patterns =
            [
                new()
                {
                    Pattern = @"(?:[(,]|^)\s*I\p{Lu}\w*(?:<[^>]*>)?\??\s+[\p{L}_]\w*\s*=\s*null\b",
                },
            ],
        },
        new()
        {
            Id = @"no-bom",
            Scope = @"file",
            Lang = @"both",
            Kind = @"bom",
            Message = @"files are saved without a byte-order mark",
        },
    ];
}
